name: UNIT TESTS
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --locked --all-groups
      - name: Run Tests
        run: uv run --locked pytest tests/

  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --locked --all-groups
      - name: Run MyPy
        run: uv run --locked  mypy .
      - name: Run Ruff Checks
        run: uvx ruff check --fix
      - name: Ruff Linting
        run: uvx ruff format
    needs:
      - test